env:
  global:
    - CC_TEST_REPORTER_ID=4f4fd4569ce4df42e5d48ce338ce260b31aa1c11b3f145bcd549f10641ab853b

language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE night;"
  - mysql -u root -e "CREATE USER 'night'@'localhost' IDENTIFIED BY 'night';"
  - mysql -u root -e "GRANT ALL ON night.* TO 'night'@'localhost';"
  - mysql -u root night < content/sql/night-sky.sql

php:
  - '7.0'
  - '7.1'
  - '7.2'

script: phpunit content/tests/Main.php
