language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE night;"
  - mysql -u root -e "CREATE USER 'night'@'localhost' IDENTIFIED BY 'night';"
  - mysql -u root -e "GRANT ALL ON night.* TO 'night'@'localhost';"
  - mysql -u root night < content/sql/travis.sql

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

script: phpunit content/tests/Main.php
